import { z } from 'zod';

/**
 * Types of browser automation actions Nebula can perform.
 */
export enum ActionType {
  OPEN_BROWSER = 'OPEN_BROWSER',
  NAVIGATE = 'NAVIGATE',
  CLICK = 'CLICK',
  SEND_KEYS = 'SEND_KEYS',
  SCROLL = 'SCROLL',
  SCREENSHOT = 'SCREENSHOT',
  DOUBLE_CLICK = 'DOUBLE_CLICK',
}

/**
 * Represents a discrete browser automation action step.
 */
export interface Action {
  type: ActionType;
  payload: Record<string, any>;
  timestamp: Date;
  description?: string;
}

/**
 * Represents the agent's target goal.
 */
export interface AgentGoal {
  goal: string;
  maxSteps?: number;
  timestamp: Date;
}

/**
 * Zod schema for validation of Gemini action outputs.
 */
export const PlannedActionSchema = z.object({
  action: z.nativeEnum(ActionType),
  selector: z.string().optional(),
  value: z.string().optional(),
});

export const ActionPlanSchema = z.object({
  reasoning: z.string().min(1, 'Reasoning is required'),
  actions: z.array(PlannedActionSchema),
});

/**
 * Represents a single action generated by the AI.
 */
export type PlannedAction = z.infer<typeof PlannedActionSchema>;

/**
 * Represents the structured plan returned by the AI.
 */
export type ActionPlan = z.infer<typeof ActionPlanSchema>;

/**
 * Represents the final reasoning explanation.
 */
export interface ReasoningResult {
  reasoning: string;
  confidence: number;
}

/**
 * Represents the outcome of verifying a browser action.
 */
export interface VerificationResult {
  verified: boolean;
  message: string;
  actualState?: Record<string, any>;
}

/**
 * Represents a log entry of a single action run.
 */
export interface ActionHistoryEntry {
  timestamp: Date;
  action: PlannedAction;
  status: 'success' | 'failed' | 'recovered';
  retryCount: number;
  verificationResult?: VerificationResult;
  recoveryAttempts: number;
  error?: string;
}

/**
 * Represents details of self-healing and recovery events.
 */
export interface RecoveryReport {
  totalRecoveries: number;
  successfulRecoveries: number;
  failedRecoveries: number;
  replansTriggered: number;
}

/**
 * Represents the structured result containing details of action execution.
 */
export interface ExecutionResult {
  success: boolean;
  completedActions: PlannedAction[];
  failedActions: PlannedAction[];
  duration: number;
  errors: string[];
  actionHistory: ActionHistoryEntry[];
  recoveryReport?: RecoveryReport;
}
